---
- name: Yum Install
  hosts: all
  gather_facts: false
  become: true
  tasks:
  - name: Yum Install Pre Dependencies
    yum: name={{ item }}
    with_items:
      - epel-release
      - gcc
      - pcre-devel
      - openssl-devel
      - zlib-devel
      - wget

  - name: Yum Install Dependencies
    yum: name={{ item }}
    with_items:
      - python-pip
      - git
      - cloud-utils
      - nodejs
