---
- name: Install Python
  hosts: all
  gather_facts: false
  become: true
  tasks:
  - name: Install Python 2.7
    unarchive:
     src: https://www.python.org/ftp/python/2.7.10/Python-2.7.10.tgz
     dest: /usr/src
     remote_src: yes

  - name: Configure Python 2.7
    shell: ./configure
    args:
      chdir: /usr/src/Python-2.7.10
    creates: /usr/src/Python-2.7.10/Modules