---
- name: Pip Install
  hosts: all
  gather_facts: false
  become: true
  tasks:
  - name: Pip Install Dependencies
    pip: 'name={{ item }}'
    with_items:
      - virtualenv
      - AWSCLI
      - ftputil
