---
- name: Pre-reqs for ansible to run
  hosts: all
  gather_facts: false
  become: yes
  pre_tasks:
    - raw: test -e /usr/bin/python || ( yum -y update && yum install -y python-minimal )

- name: Build Data Ingest Linux Server.
  hosts: all
  become: true
  tasks:
  - name: SSM Group
    group:
      name: SSM
      system: yes

  - name: Create wherescape user
    user:
      name: wherescape
      group: SSM

  - name: Make directory structure
    file:
      path: /{{ item }}
      state: directory
      mode: 0775
      recurse: yes
      owner: wherescape
      group: SSM
    with_items:
      - ADT
      - EF
      - NATS
      - appdata
      - appdata/ADT
      - appdata/ADT/archive
      - appdata/ADT/archive/07032016acl
      - appdata/ADT/archive/07032016oag
      - appdata/ADT/archive/acl
      - appdata/ADT/archive/mvt
      - appdata/ADT/archive/oag
      - appdata/ADT/data
      - appdata/ADT/data/07032016acl
      - appdata/ADT/data/07032016oag
      - appdata/ADT/data/acl
      - appdata/ADT/data/mvt
      - appdata/ADT/data/oag
      - appdata/ADT/quarantine
      - appdata/ADT/quarantine/acl
      - appdata/ADT/quarantine/mvt
      - appdata/ADT/quarantine/oag
      - appdata/ADT/scripts
      - appdata/ADT/stage
      - appdata/ADT/stage/acl
      - appdata/ADT/stage/maytech
      - appdata/ADT/stage/mvt
      - appdata/ADT/stage/oag
      - appdata/EF
      - appdata/EF/data
      - appdata/EF/data/drt
      - appdata/EF/keys
      - appdata/EF/log
      - appdata/EF/scripts
      - appdata/NATS
      - appdata/NATS/archive
      - appdata/NATS/archive/nats
      - appdata/NATS/data
      - appdata/NATS/data/nats
      - appdata/NATS/data/ga
      - appdata/NATS/log
      - appdata/NATS/quarantine
      - appdata/NATS/quarantine/nats
      - appdata/NATS/scripts
      - appdata/NATS/stage
      - appdata/NATS/stage/maytech
      - appdata/NATS/stage/nats

  - file:
      src: /appdata/ADT
      dest: /ADT
      force: yes
      owner: wherescape
      group: SSM
      state: link

  - file:
      src: /appdata/EF
      dest: /EF
      force: yes
      owner: wherescape
      group: SSM
      state: link

  - file:
      src: /appdata/NATS
      dest: /NATS
      force: yes
      owner: wherescape
      group: SSM
      state: link

  - name: Create .ssh directory for Wherescape user
    file:
      path: /home/wherescape/.ssh
      state: directory
      mode: 0700
      owner: wherescape
      group: SSM

  - name: Create authorized_keys file for Wherescape user
    copy:
      content: ""
      dest: /home/wherescape/.ssh/authorized_keys
      force: no
      mode: 0600
      owner: wherescape
      group: SSM

  - name: Yum Install Pre Dependencies
    yum: name={{ item }}
    with_items:
      - epel-release
      - gcc
      - pcre-devel
      - openssl-devel
      - zlib-devel
      - wget
    become: true

  - name: Yum Install Dependencies
    yum: name={{ item }}
    with_items:
      - python-pip
      - git
      - cloud-utils
      - nodejs
    become: true

  - name: Install Python 2.7
    unarchive:
     src: https://www.python.org/ftp/python/2.7.10/Python-2.7.10.tgz
     dest: /usr/src
     remote_src: yes
    become: true

  - name: Configure Python 2.7
    shell: ./configure
    args:
      chdir: /usr/src/Python-2.7.10
    creates: /usr/src/Python-2.7.10/Modules
    become: true

  - name: Pip Install Dependencies
    pip: 'name={{ item }}'
    with_items:
      - AWSCLI
      - ftputil
      - virtualenv
    become: true

  - name: GET config files from DQ-config-bucket
    shell: '{{ item }}'
    with_items:
      - aws configure set aws_access_key_id '{{user_access_key}}'
      - aws configure set aws_secret_access_key '{{secret_access_key}}'
      - aws s3 cp s3://dq-config-bucket/dq-data-ingest-linux-server /tmp/install --recursive

  - name: Remove AWS config
    shell: rm ~/.aws/credentials
    become: true

  - name: Install Postgresql 9.6
    shell: '{{ item }}'
    with_items:
      - rpm -ivh https://yum.postgresql.org/9.6/redhat/rhel-7.3-x86_64/pgdg-centos96-9.6-3.noarch.rpm
      - yum update -y
      - yum install -y postgresql96

  - name: ClamAV Install Packages
    shell: '{{ item }}'
    with_items:
      - yum -y install clamav-server clamav-data clamav-update clamav-filesystem clamav clamav-scanner-systemd clamav-devel clamav-lib clamav-server-systemd

  - name: ClamAV SELinux configuration
    shell: '{{ item }}'
    with_items:
      - setenforce 0
      - setsebool -P antivirus_can_scan_system 1
      - setsebool -P clamd_use_jit 0

  - name: ClamAV Configuration
    copy:
      src: '/tmp/install/scan.conf'
      dest: '{{ item }}'
      remote_src: yes
      force: yes
    with_items:
      - /etc/clamd.d/scan.conf
      - /etc/clamd.d/scan.conf.backup
      - /etc/clamd.conf

  - name: Freshclam Additional Configuration
    shell: '{{ item }}'
    with_items:
      - sed -i -e "s/^Example/#Example/" /etc/freshclam.conf
      - freshclam

  - name: Freshclam Configuration Files
    shell: cp /etc/freshclam.conf /etc/freshclam.conf.backup && \
           cp /tmp/install/freshclam.service /usr/lib/systemd/system/freshclam.service

  - name: Cron Freshclam
    cron:
      minute: "0"
      hour: "01,13"
      day: "*"
      job: "/usr/bin/freshclam --quiet"

  - name: Start, Enable Freshclam
    shell: '{{ item }}'
    with_items:
      - systemctl start freshclam
      - systemctl enable freshclam

  - name: Start, Enable Clamd
    shell: '{{ item }}'
    with_items:
      - systemctl start clamd@scan
      - systemctl enable clamd@scan

  - name: Add Wherescape user to clamscan group now it exists
    user:
      name: wherescape
      groups: clamscan
      append: yes

  - name: Clone Data Transfer from Github
    git:
      repo: https://github.com/UKHomeOffice/data-transfer
      dest: '/appdata/data-transfer'
      force: yes
    become: true
    become_user: wherescape

 # Copy's the config file over and change permissions, before the venv is created.
  - name: Data Transfer Configuration
    command: cp /tmp/install/ecosystem.config.js /appdata/data-transfer

  - file:
      path: '/appdata/data-transfer/ecosystem.config.js'
      owner: wherescape
      group: SSM

  - name: Npm Install Data Transfer Dependencies
    npm:
      name: pm2
      global: yes

  - name: Configure Data Transfer
    shell: cd /appdata/data-transfer && \
           python2.7 -m virtualenv ~/.virtualenvs/data-transfer && \
           source ~/.virtualenvs/data-transfer/bin/activate && \
           pip install -r /appdata/data-transfer/requirements.txt
    become: true
    become_user: wherescape

  - name: Check PM2 Startup Script is present
    command: pm2 startup -u wherescape --hp /home/wherescape
    args:
      creates: /etc/systemd/system/pm2-wherescape.service
    tags: pm2_startup_script

  - name: Start Data Transfer
    shell: cd /appdata/data-transfer && \
           source ~/.virtualenvs/data-transfer/bin/activate && \
           export PYTHONPATH=. && \
           pm2 start -u wherescape ecosystem.config.js
    become: true
    become_user: wherescape
    args:
      chdir: /appdata/data-transfer

  - name: Saving PM2 state to enable restart
    command: pm2 save
    become: true
    become_user: wherescape
    args:
      chdir: /appdata/data-transfer

 # Other script setup
  - name: Clone script repos from Github
    git:
      repo: '{{ item.repo }}'
      dest: '{{ item.dest }}'
      clone: yes
      update: no
    with_items:
      - { repo: 'https://github.com/UKHomeOffice/dq_sftp-nats-dmz/', dest: '/opt/dq_sftp-nats-dmz' }
      - { repo: 'https://github.com/UKHomeOffice/dq-ssm_ingest/', dest: '/opt/dq-ssm_ingest' }
    become: true

  - name: Symlink script files in opt
    file:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      force: yes
      state: link
    with_items:
      - { src: '/opt/dq_sftp-nats-dmz/NATS/scripts/', dest: '/appdata/NATS/scripts'}
      - { src: '/opt/dq-ssm_ingest/ADT/WEB_Server/', dest: '/appdata/ADT/scripts'}

  - name: '{{ item.name }}'
    cron:
      user: '{{ item.user }}'
      minute: '{{ item.minute }}'
      hour: '{{ item.hour }}'
      day: '{{ item.day }}'
      job: '{{ item.job }}'
    with_items:
        - { name: Cron sftp_nats_client_maytech.py, user: wherescape, minute: "*/1",  hour: "*", day: "*",  job: "cd /NATS/scripts && ./check_run.sh ./sftp_nats_client_maytech.py > /dev/null 2> /dev/null" }
        - { name: Cron nats_house_keeping, user: wherescape, minute: "*/45",  hour: "*", day: "*", job: "/NATS/scripts/nats_house_keeping.sh > /dev/null 2> /dev/null" }
        - { name: Cron ftp_acl_web02.py, user: wherescape, minute: "*/10",  hour: "0", day: "*",  job: "/ADT/scripts/ftp_acl_web02.py" }
        - { name: Cron sftp_oag_client_maytech.py, user: wherescape, minute: "*/2",  hour: "*", day: "*",  job: "/ADT/scripts/sftp_oag_client_maytech.py" }
        
  - name: Set DNS Resolver Options
    blockinfile:
      path: /etc/sysconfig/network
      block: |
        RES_OPTIONS="rotate timeout:1 attempts:1"
