---

- name: Pre-reqs for ansible to run
  hosts: all
  gather_facts: false
  become: yes
  pre_tasks:
    - raw: test -e /usr/bin/python || ( yum -y update && yum install -y python-minimal )

- name: Build Data Ingest Linux Server.
  hosts: all
  become: yes
  tasks:
    - yum: name=gcc
    - yum: name=pcre-devel
    - yum: name=openssl-devel
    - yum: name=zlib-devel
    - yum: name=wget
    - yum: name=https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm
    - yum: name=python-pip

    - name: Create ADT directories
      file:
        path: /appdata/ADT/
        state: directory
        mode: 0775
        recurse: yes

    - name: Create ADT archive directory
      file:
        path: /appdata/ADT/archive
        state: directory
        mode: 0775
        recurse: yes

    - name: Create ADT archive subdirectory (1/5)
      file:
        path: /appdata/ADT/archive/07032016acl
        state: directory
        mode: 0775
        recurse: yes

    - name: Create ADT archive subdirectory (2/5)
      file:
        path: /appdata/ADT/archive/07032016oag
        state: directory
        mode: 0775
        recurse: yes

    - name: Create ADT archive subdirectory (3/5)
      file:
        path: /appdata/ADT/archive/acl
        state: directory
        mode: 0775
        recurse: yes

    - name: Create ADT archive subdirectory (4/5)
      file:
        path: /appdata/ADT/archive/mvt
        state: directory
        mode: 0775
        recurse: yes

    - name: Create ADT archive subdirectory (5/5)
      file:
        path: /appdata/ADT/archive/oag
        state: directory
        mode: 0775
        recurse: yes

    - name: Create ADT data directory
      file:
        path: /appdata/ADT/data
        state: directory
        mode: 0775
        recurse: yes

    - name: Create ADT data subdirectory (1/5)
      file:
        path: /appdata/ADT/data/07032016acl
        state: directory
        mode: 0775
        recurse: yes

    - name: Create ADT data subdirectory (2/5)
      file:
        path: /appdata/ADT/data/07032016oag
        state: directory
        mode: 0775
        recurse: yes

    - name: Create ADT data subdirectory (3/5)
      file:
        path: /appdata/ADT/data/acl
        state: directory
        mode: 0775
        recurse: yes

    - name: Create ADT data subdirectory (4/5)
      file:
        path: /appdata/ADT/data/mvt
        state: directory
        mode: 0775
        recurse: yes

    - name: Create ADT data subdirectory (5/5)
      file:
        path: /appdata/ADT/data/oag
        state: directory
        mode: 0775
        recurse: yes

    - name: Create ADT quarantine directory
      file:
        path: /appdata/ADT/quarantine
        state: directory
        mode: 0775
        recurse: yes

    - name: Create ADT quarantine subdirectory (1/3)
      file:
        path: /appdata/ADT/quarantine/acl
        state: directory
        mode: 0775
        recurse: yes

    - name: Create ADT quarantine subdirectory (2/3)
      file:
        path: /appdata/ADT/quarantine/mvt
        state: directory
        mode: 0775
        recurse: yes

    - name: Create ADT quarantine subdirectory (3/3)
      file:
        path: /appdata/ADT/quarantine/oag
        state: directory
        mode: 0775
        recurse: yes

    - name: Create ADT scripts directory
      file:
        path: /appdata/ADT/scripts
        state: directory
        mode: 0775
        recurse: yes

    - name: Create ADT stage directory
      file:
        path: /appdata/ADT/stage
        state: directory
        mode: 0775
        recurse: yes

    - name: Create ADT stage subdirectory (1/4)
      file:
        path: /appdata/ADT/stage/acl
        state: directory
        mode: 0775
        recurse: yes

    - name: Create ADT stage subdirectory (2/4)
      file:
        path: /appdata/ADT/stage/maytech
        state: directory
        mode: 0775
        recurse: yes

    - name: Create ADT stage subdirectory (3/4)
      file:
        path: /appdata/ADT/stage/mvt
        state: directory
        mode: 0775
        recurse: yes

    - name: Create ADT stage subdirectory (4/4)
      file:
        path: /appdata/ADT/stage/oag
        state: directory
        mode: 0775
        recurse: yes

    - name: Create EF directory
      file:
        path: /appdata/EF
        state: directory
        mode: 0775
        recurse: yes

    - name: Create EF data directory
      file:
        path: /appdata/EF/data
        state: directory
        mode: 0775
        recurse: yes

    - name: Create EF data subdirectory
      file:
        path: /appdata/EF/data/drt
        state: directory
        mode: 0775
        recurse: yes

    - name: Create EF keys directory
      file:
        path: /appdata/EF/keys
        state: directory
        mode: 0775
        recurse: yes

    - name: Create EF log directory
      file:
        path: /appdata/EF/log
        state: directory
        mode: 0775
        recurse: yes

    - name: Create EF scripts directory
      file:
        path: /appdata/EF/scripts
        state: directory
        mode: 0775
        recurse: yes

    - name: Create EF transfer directory
      file:
        path: /appdata/EF/scripts
        state: directory
        mode: 0775
        recurse: yes

    - name: Create NATS directory
      file:
        path: /appdata/NATS
        state: directory
        mode: 0775
        recurse: yes

    - name: Create NATS archive directory
      file:
        path: /appdata/NATS/archive
        state: directory
        mode: 0775
        recurse: yes

    - name: Create NATS archive subdirectory
      file:
        path: /appdata/NATS/archive/nats
        state: directory
        mode: 0775
        recurse: yes

    - name: Create NATS data directory
      file:
        path: /appdata/NATS/data
        state: directory
        mode: 0775
        recurse: yes

    - name: Create NATS data subdirectory
      file:
        path: /appdata/NATS/data/nats
        state: directory
        mode: 0775
        recurse: yes

    - name: Create NATS log directory
      file:
        path: /appdata/NATS/log
        state: directory
        mode: 0775
        recurse: yes

    - name: Create NATS quarantine directory
      file:
        path: /appdata/NATS/quarantine
        state: directory
        mode: 0775
        recurse: yes

    - name: Create NATS quarantine subdirectory
      file:
        path: /appdata/NATS/quarantine/nats
        state: directory
        mode: 0775
        recurse: yes

    - name: Create NATS scripts directory
      file:
        path: /appdata/NATS/scripts
        state: directory
        mode: 0775
        recurse: yes

    - name: Create NATS stage directory
      file:
        path: /appdata/NATS/stage
        state: directory
        mode: 0775
        recurse: yes

    - name: Create NATS stage subdirectory (1/2)
      file:
        path: /appdata/NATS/stage/maytech
        state: directory
        mode: 0775
        recurse: yes

    - name: Create NATS stage subdirectory (2/2)
      file:
        path: /appdata/NATS/stage/nats
        state: directory
        mode: 0775
        recurse: yes
