---
- name: Post Deploy SSM Processing Features
  hosts: all
  gather_facts: false
  become: yes
  tasks:
  - name: Yum Install Dependencies for SSM ADT EXT Server scripts
    yum: name={{ item }}
    with_items:
      - python-psycopg2
      - python-argparse
      - libxml2-python

  - name: Add additional directories for Wherescape user
    file:
      path: /{{ item }}
      state: directory
      mode: 0775
      recurse: yes
      owner: wherescape
      group: SSM
    with_items:
      - appdata/ADT/log

  - name: Update NATS permissions to wherescape
    shell: "{{ item }}"
    with_items:
      - chmod 775 /NATS/scripts
      - chmod 775 /NATS/scripts/check_run.sh

  - name: Yum Install pyodbc dependencies
    yum: name={{ item }}
    with_items:
      - unixODBC
      - unixODBC-devel
      - gcc-c++
      - python-devel

  - name: Pip Install pyodbc
    pip: name={{ item }}
    with_items:
      - pyodbc

  - name: Delete wherescape cron
    shell: rm /var/spool/cron/wherescape

  - name: '{{ item.name }}'
    cron:
      user: '{{ item.user }}'
      minute: '{{ item.minute }}'
      hour: '{{ item.hour }}'
      day: '{{ item.day }}'
      job: '{{ item.job }}'
    with_items:
        - { name: Cron sftp_nats_client_maytech.py, user: wherescape, minute: "*/1",  hour: "*", day: "*",  job: sh -c ". /etc/profile.d/script_envs.sh && cd /NATS/scripts && ./check_run.sh ./sftp_nats_client_maytech.py > /dev/null 2> /dev/null" }
        - { name: Cron nats_house_keeping, user: wherescape, minute: "*/45",  hour: "*", day: "*", job: sh -c ". /etc/profile.d/script_envs.sh && /NATS/scripts/nats_house_keeping.sh > /dev/null 2> /dev/null" }
        - { name: Cron ftp_acl_web02.py, user: wherescape, minute: "*/10",  hour: "0", day: "*",  job: sh -c ". /etc/profile.d/script_envs.sh && cd /ADT/scripts && python ftp_acl_web02.py" }
        - { name: Cron sftp_oag_client_maytech.py, user: wherescape, minute: "*/2",  hour: "*", day: "*",  job: sh -c  ". /etc/profile.d/script_envs.sh && cd /ADT/scripts && python sftp_oag_client_maytech.py" }
