---
- name: Post Deploy SSM Processing Features
  hosts: all
  gather_facts: false
  become: yes
  tasks:
  - name: Yum Install Dependencies for SSM ADT EXT Server scripts
    yum: name={{ item }}
    with_items:
      - python-psycopg2
      - python-argparse
      - libxml2-python

  - name: Add additional directories for Wherescape user
    file:
      path: /{{ item }}
      state: directory
      mode: 0775
      recurse: yes
      owner: wherescape
      group: SSM
    with_items:
      - appdata/ADT/log

  - name: Set MVT_SCHEMA_SSM_PASSWORD for Wherescape user
    shell: export MVT_SCHEMA_SSM_PASSWORD=`aws --region eu-west-2 ssm get-parameter --name mvt_schema_ssm_password --query 'Parameter.Value' --output text --with-decryption | base64 --decode`
    become: true
    become_user: wherescape

  - name: Set RDS_POSTGRES_DATA_INGEST_HOST_NAME for Wherescape user
    shell: export RDS_POSTGRES_DATA_INGEST_HOST_NAME=`aws --region eu-west-2 ssm get-parameter --name rds-postgres-dataingest-hostname --query 'Parameter.Value' --output text --with-decryption`
    become: true
    become_user: wherescape

  - name: Yum Install pyodbc dependencies
    yum: name={{ item }}
    with_items:
      - unixODBC
      - unixODBC-devel
      - gcc-c++
      - python-devel

  - name: Pip Install pyodbc
    pip: name={{ item }}
    with_items:
      - pyodbc

  - name: Delete OAG history db cache
    shell: rm /ADT/scripts/oaghistory.db
    become: true
    become_user: wherescape