---
- name: Post Deploy SSM Processing Features
  hosts: all
  gather_facts: false
  become: yes
  tasks:
  - name: Yum Install Dependencies for SSM ADT EXT Server scripts
    yum: name={{ item }}
    with_items:
      - python-psycopg2
      - python-argparse
      - libxml2-python

  - name: Add additional directories for Wherescape user
    file:
      path: /{{ item }}
      state: directory
      mode: 0775
      recurse: yes
      owner: wherescape
      group: SSM
    with_items:
      - appdata/ADT/log

  - name: Yum Install pyodbc dependencies
    yum: name={{ item }}
    with_items:
      - unixODBC
      - unixODBC-devel
      - gcc-c++
      - python-devel

  - name: Pip Install pyodbc
    pip: name={{ item }}
    with_items:
      - pyodbc