---
- name: Post Deploy SSM Processing Features
  hosts: all
  gather_facts: false
  become: yes
  tasks:
  - name: Reset permissions of /ADT/scripts to wherescape for log files
    file:
      path: /opt/dq-ssm_ingest/ADT/WEB_Server/
      owner: wherescape
      group: SSM
      mode: 0775

  - name: Yum Install Dependencies for SSM ADT EXT Server scripts
    yum: name={{ item }}
    with_items:
      - python-psycopg2
      - python-argparse
      - libxml2-python

  - name: Add additional directories for Wherescape user
    file:
      path: /{{ item }}
      state: directory
      mode: 0775
      recurse: yes
      owner: wherescape
      group: SSM
    with_items:
      - appdata/ADT/log